from setuptools import setup, find_packages

setup(
    name='medifit_fusion_1',
    version='0.1',
    packages=find_packages(),
    install_requires=[
        'Bottleneck',
        'contourpy',
        'cycler',
        'et-xmlfile==1.1.0',
        'fonttools==4.25.0',
        'joblib',
        'kiwisolver',
        'matplotlib',
        'mkl-fft==1.3.6',
        'mkl-random',
        'mkl-service==2.4.0',
        'munkres==1.1.4',
        'numexpr',
        'numpy',
        'openpyxl==3.0.10',
        'packaging',
        'pandas',
        'Pillow==9.4.0',
        'ply==3.11',
        'pyparsing',
        'PyQt5==5.15.7',
        'PyQt5-sip',
        'python-dateutil',
        'pytz',
        'scikit-learn',
        'scipy==1.11.1',
        'seaborn',
        'sip',
        'six',
        'tabulate',
        'threadpoolctl',
        'toml',
        'tornado'
    ],
    author='Antonios Morellos',
    author_email='antonios.morellos@gmail.com',
    description='A brief description of your package',
    #url='https://github.com/your_username/my_package',  # Optional
)